service:
  externalPort: 8000
  internalPort: 8080

mappingsFromConfigmap: false
responsesFromConfigmap: false

args:
  - "--port=8080"
  - "--max-request-journal=1000"
  - "--global-response-templating"

podSecurityContext:
  seccompProfile:
    type: RuntimeDefault

securityContext:
  runAsNonRoot: true
  runAsUser: 1000
  runAsGroup: 1000
  allowPrivilegeEscalation: false
  capabilities:
    drop: ["ALL"]
  readOnlyRootFilesystem: false

resources:
  requests:
    cpu: 100m
    memory: 128Mi