apiVersion: batch/v1
kind: Job
metadata:
  name: {{ include "support-bot-functional-tests.fullname" . }}
  labels:
    {{- include "support-bot-functional-tests.labels" . | nindent 4 }}
spec:
  backoffLimit: {{ .Values.job.backoffLimit }}
  activeDeadlineSeconds: {{ .Values.job.activeDeadlineSeconds }}
  parallelism: {{ .Values.job.parallelism }}
  completions: {{ .Values.job.completions }}
  template:
    metadata:
      labels:
        {{- include "support-bot-functional-tests.selectorLabels" . | nindent 8 }}
    spec:
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      restartPolicy: {{ .Values.job.restartPolicy }}
      containers:
        - name: functional-tests
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          env:
            - name: SERVICE_ENDPOINT
              value: "http://support-bot:8080"
          ports:
            - name: slack
              containerPort: 8000
          volumeMounts:
            - name: tmp
              mountPath: /tmp
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
      volumes:
        - name: tmp
          emptyDir: {}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
