image:
  repository: support-bot-functional-tests
  tag: latest
  pullPolicy: IfNotPresent

nameOverride: ""
fullnameOverride: ""

podSecurityContext:
  runAsNonRoot: true
  runAsUser: 1001
  runAsGroup: 1001
  fsGroup: 1001
  seccompProfile:
    type: RuntimeDefault

securityContext:
  allowPrivilegeEscalation: false
  readOnlyRootFilesystem: true
  capabilities:
    drop: ["ALL"]

job:
  restartPolicy: Never
  backoffLimit: 0
  activeDeadlineSeconds: 60
  parallelism: 1
  completions: 1

resources:
  requests:
    cpu: 256m
    memory: 256m

nodeSelector: {}

tolerations: []

affinity: {}
