.PHONY: test
test: # Runs tests and expects a running application
	../gradlew :functional:test

.PHONY: test-integrated
test-integrated: # Start the service and run tests in the same command
	../gradlew :functional:testIntegrated
