spring:
  main:
    banner-mode: off
  application:
    name: support-bot

server:
  # We only use Jetty for the actuator for now, so limit its resources
  jetty:
    threads:
      acceptors: 1
      selectors: 1
      min: 1
      max: 4

management:
  endpoint:
    health:
      probes:
        enabled: true

slack:
  creds:
    token: ${SLACK_TOKEN} # Token like: xoxb-abc-def
    socket-token: ${SLACK_SOCKET_TOKEN} # Token like: xapp-1-abc-def-ghi
    signing-secret: ${SLACK_SIGNING_SECRET} # Token like: 1234567890abcdef
  ticket:
    channel-id: ${TICKET_CHANNEL_ID} # Channel ID like: C1234567890
    expected-initial-reaction: eyes
    response-initial-reaction: ticket
  escalation:
    channel-id: ${ESCALATION_CHANNEL_ID} # Channel ID like: C1234567890

ticket:
  tags:
    - name: Tag A
      code: tagA
    - name: Tag B
      code: tagB
    - name: Tag C
      code: tagC
  impacts:
    - name: Production Blocking
      code: productionBlocking
    - name: BAU Blocking
      code: bauBlocking
    - name: Abnormal Behaviour
      code: abnormalBehaviour

escalation:
  topics:
    - name: Topic A
      code: topicA
    - name: Topic B
      code: topicB
    - name: Topic C
      code: topicC
  teams:
    - name: Team A
      code: teamA
    - name: Team B
      code: teamB
    - name: Team C
      code: teamC