package com.coreeng.supportbot.analysis.llm;

import dev.langchain4j.data.message.AiMessage;
import dev.langchain4j.data.message.ChatMessage;
import dev.langchain4j.data.message.UserMessage;
import dev.langchain4j.model.chat.ChatModel;
import dev.langchain4j.model.chat.request.ChatRequest;
import dev.langchain4j.model.chat.response.ChatResponse;
import java.util.List;

/**
 * A {@link ChatModel} that reaches no network and returns canned, deterministic text.
 *
 * <p>For local development and demos: it lets the analysis run and the Support Summary page be
 * exercised end to end with no credentials and no LLM spend. Every response is a pure function of
 * the request, so a re-run produces identical classifications — which also keeps the summary's
 * data fingerprint stable instead of invalidating the cache on every visit.
 *
 * <p>May be dropped before merge — see {@code docs/plans/support-summary.md}.
 *
 * <h2>Telling the two callers apart</h2>
 *
 * Both consumers call {@link #chat(String)} with a single blob, so the stub has to work out which
 * one it is answering. It keys on the delimiter the summary call site wraps its report in, because
 * that string is owned by our own code ({@code LlmSummaryService}) rather than by prompt text stored
 * in the database — prompts get rewritten by migration, delimiters do not. Anything without that
 * marker is treated as a classification request: that is the safer default, since an unrecognised
 * classification would produce unparseable output and silently skip every ticket, while an
 * unrecognised summary merely produces odd prose. {@code StubChatModelTest} drives the real
 * {@code LlmAnalysisService} and {@code LlmSummaryService} rather than hand-built strings, so a
 * change to either delimiter fails there instead of quietly degrading.
 */
public class StubChatModel implements ChatModel {

    /** Set by {@code LlmSummaryService} around the aggregated window report. */
    private static final String SUMMARY_MARKER = "--- BEGIN WINDOW REPORT ---";

    // Values drawn from the controlled taxonomy in the seeded classification prompt (V37), so the
    // stubbed breakdowns look like real ones rather than free text the UI has never seen.
    private static final List<String> DRIVERS = List.of(
            "Knowledge Gap", "Product Usability Problem", "Product Temporary Issue", "Feature Request", "Task Request");

    private static final List<String> CATEGORIES = List.of(
            "Tenancy & Onboarding",
            "Build & CI",
            "Deployment & CD",
            "Connectivity & Networking",
            "Platform Tooling",
            "Deploying & Configuring Applications",
            "Monitoring & Troubleshooting",
            "Security & Compliance",
            "Observability");

    private static final List<String> FEATURES = List.of(
            "deployment pipelines",
            "ingress routing",
            "secrets management",
            "workload compute",
            "log aggregation",
            "identity provider groups",
            "None");

    private static final String CANNED_SUMMARY = """
            Demand over this window was dominated by tenants trying to get workloads through the \
            path to production, with most threads turning on configuration details rather than \
            platform faults. The recurring shape is a tenant who knows a capability exists but \
            cannot tell which of several similar-looking options applies to their case.

            A smaller cluster concerns connectivity and access: requests that only the platform team \
            is authorised to action, which arrive as questions but are really task requests. These \
            are cheap individually and add up, and are the most obvious candidate for self-service.

            This text is generated by the stub LLM provider and describes no real tickets. Enable a \
            real provider to get an actual summary.""";

    @Override
    public ChatResponse doChat(ChatRequest chatRequest) {
        String prompt = textOf(chatRequest.messages());
        String answer = prompt.contains(SUMMARY_MARKER) ? CANNED_SUMMARY : classification(prompt);
        return ChatResponse.builder()
                .aiMessage(AiMessage.from(answer))
                .modelName("stub")
                .build();
    }

    /**
     * Emits exactly the strict block the classification prompt asks for, so it parses through the
     * real parser. The values vary with the request so the breakdowns spread across buckets instead
     * of collapsing into a single bar — a one-bucket demo would hide any grouping bug in the page.
     */
    private static String classification(String prompt) {
        int seed = Math.floorMod(prompt.hashCode(), Integer.MAX_VALUE);
        String driver = pick(DRIVERS, seed);
        String category = pick(CATEGORIES, seed / DRIVERS.size());
        String feature = pick(FEATURES, seed / (DRIVERS.size() * CATEGORIES.size()));

        return """
                Ticket: 0
                Primary Driver: %s
                Category: %s
                Platform Feature: %s
                Reason: Stubbed classification — the tenant raised a %s issue around %s. This text is \
                generated locally and describes no real thread.""".formatted(driver, category, feature, category.toLowerCase(java.util.Locale.ROOT), feature);
    }

    private static String pick(List<String> values, int seed) {
        return values.get(Math.floorMod(seed, values.size()));
    }

    private static String textOf(List<ChatMessage> messages) {
        StringBuilder text = new StringBuilder();
        for (ChatMessage message : messages) {
            if (message instanceof UserMessage userMessage && userMessage.hasSingleText()) {
                text.append(userMessage.singleText()).append('\n');
            }
        }
        return text.toString();
    }
}
