# Backstage override configuration for your production environment

app:
  baseUrl: "${BASE_URL}"

backend:
  baseUrl: "${BASE_URL}"
  csp:
    img-src: ["'self'", 'data:', 'https:']



# no auth & permission setup for now
#    # Local example data, replace this with your production config, these are intended for demo use only.
auth:
  providers:
    guest:
      dangerouslyAllowOutsideDevelopment: true
