package com.coreeng.supportbot.config;

import com.coreeng.supportbot.github.GitHubClient;
import com.coreeng.supportbot.github.Hub4jGitHubClient;
import io.jsonwebtoken.Jwts;
import java.io.IOException;
import java.io.StringReader;
import java.security.PrivateKey;
import java.time.Instant;
import java.time.temporal.ChronoUnit;
import java.util.Date;
import org.bouncycastle.openssl.PEMKeyPair;
import org.bouncycastle.openssl.PEMParser;
import org.bouncycastle.openssl.jcajce.JcaPEMKeyConverter;
import org.kohsuke.github.GitHub;
import org.kohsuke.github.GitHubBuilder;
import org.kohsuke.github.authorization.AppInstallationAuthorizationProvider;
import org.kohsuke.github.authorization.AuthorizationProvider;
import org.springframework.boot.autoconfigure.condition.ConditionalOnProperty;
import org.springframework.context.annotation.Bean;
import org.springframework.context.annotation.Configuration;

@Configuration
@ConditionalOnProperty(name = "pr-review-tracking.enabled", havingValue = "true")
public class PrTrackingGitHubConfig {

    @Bean
    public GitHub gitHub(PrTrackingProps props) {
        PrTrackingGitHubProps config = props.github();
        try {
            if (config.authMode() == PrTrackingAuthMode.APP) {
                return buildAppModeClient(config);
            }
            return new GitHubBuilder()
                    .withEndpoint(config.apiBaseUrl())
                    .withOAuthToken(config.token())
                    .build();
        } catch (IOException e) {
            throw new IllegalStateException("Failed to initialize GitHub client", e);
        }
    }

    @Bean
    public GitHubClient gitHubClient(GitHub gitHub) {
        return new Hub4jGitHubClient(gitHub);
    }

    private static GitHub buildAppModeClient(PrTrackingGitHubProps config) throws IOException {
        PrivateKey privateKey = parsePrivateKey(config.privateKeyPem());
        long installationId = Long.parseLong(config.installationId());
        String appId = config.appId();

        AuthorizationProvider jwtProvider = () -> "Bearer " + createJwt(appId, privateKey);

        AppInstallationAuthorizationProvider authProvider = new AppInstallationAuthorizationProvider(
                app -> app.getInstallationById(installationId), jwtProvider);

        return new GitHubBuilder()
                .withEndpoint(config.apiBaseUrl())
                .withAuthorizationProvider(authProvider)
                .build();
    }

    private static String createJwt(String appId, PrivateKey privateKey) {
        Instant now = Instant.now();
        return Jwts.builder()
                .issuer(appId)
                .issuedAt(Date.from(now))
                .expiration(Date.from(now.plus(10, ChronoUnit.MINUTES)))
                .signWith(privateKey, Jwts.SIG.RS256)
                .compact();
    }

    /**
     * Accepts both PKCS#1 ("BEGIN RSA PRIVATE KEY", as generated by GitHub)
     * and PKCS#8 ("BEGIN PRIVATE KEY"). BouncyCastle handles both transparently.
     *
     * {@code private-key-pem} must be a well-formed PEM — use a YAML block scalar
     * (the {@code |} indicator) so Spring preserves real newlines.
     */
    private static PrivateKey parsePrivateKey(String pem) {
        try (PEMParser parser = new PEMParser(new StringReader(pem))) {
            Object obj = parser.readObject();
            if (obj instanceof PEMKeyPair keyPair) {
                return  new JcaPEMKeyConverter().getPrivateKey(keyPair.getPrivateKeyInfo());
            }
            if (obj instanceof org.bouncycastle.asn1.pkcs.PrivateKeyInfo keyInfo) {
                return new JcaPEMKeyConverter().getPrivateKey(keyInfo);
            }
            throw new IllegalArgumentException(
                    "Unrecognised PEM object — check that private-key-pem is supplied as a YAML block scalar (| indicator). "
                            + "Got: " + (obj == null ? "null (no PEM header found)" : obj.getClass().getName()));
        } catch (IOException e) {
            throw new IllegalArgumentException("Failed to parse GitHub App private key from PEM", e);
        }
    }
}
