package com.coreeng.supportbot.prtracking;

import com.coreeng.supportbot.config.PrTrackingProps;
import com.coreeng.supportbot.github.GitHubClient;
import com.coreeng.supportbot.github.Hub4jGitHubClient;
import io.jsonwebtoken.Jwts;
import java.io.IOException;
import java.io.StringReader;
import java.nio.charset.StandardCharsets;
import java.security.PrivateKey;
import java.time.Instant;
import java.time.temporal.ChronoUnit;
import java.util.Base64;
import java.util.Date;
import org.bouncycastle.openssl.PEMKeyPair;
import org.bouncycastle.openssl.PEMParser;
import org.bouncycastle.openssl.jcajce.JcaPEMKeyConverter;
import org.kohsuke.github.GitHub;
import org.kohsuke.github.GitHubBuilder;
import org.kohsuke.github.authorization.AppInstallationAuthorizationProvider;
import org.kohsuke.github.authorization.AuthorizationProvider;
import org.springframework.boot.autoconfigure.condition.ConditionalOnProperty;
import org.springframework.context.annotation.Bean;
import org.springframework.context.annotation.Configuration;

@Configuration
@ConditionalOnProperty(name = "pr-review-tracking.enabled", havingValue = "true")
public class PrTrackingGitHubConfig {

    @Bean
    public GitHub gitHub(PrTrackingProps props) {
        PrTrackingProps.GitHub config = props.github();
        try {
            if (config.authMode() == PrTrackingProps.AuthMode.APP) {
                return buildAppModeClient(config);
            }
            return new GitHubBuilder()
                    .withEndpoint(config.apiBaseUrl())
                    .withOAuthToken(config.token())
                    .build();
        } catch (IOException e) {
            throw new IllegalStateException("Failed to initialize GitHub client", e);
        }
    }

    @Bean
    public GitHubClient gitHubClient(GitHub gitHub) {
        return new Hub4jGitHubClient(gitHub);
    }

    private static GitHub buildAppModeClient(PrTrackingProps.GitHub config) throws IOException {
        PrivateKey privateKey = parsePrivateKey(config.privateKeyPem());
        long installationId = Long.parseLong(config.installationId());
        String appId = config.appId();

        AuthorizationProvider jwtProvider = () -> "Bearer " + createJwt(appId, privateKey);

        AppInstallationAuthorizationProvider authProvider =
                new AppInstallationAuthorizationProvider(app -> app.getInstallationById(installationId), jwtProvider);

        return new GitHubBuilder()
                .withEndpoint(config.apiBaseUrl())
                .withAuthorizationProvider(authProvider)
                .build();
    }

    private static String createJwt(String appId, PrivateKey privateKey) {
        Instant now = Instant.now();
        // Backdate iat by 60s to tolerate clock skew between the bot and GitHub.
        // Expiry is set to 9 minutes so the total window stays within GitHub's 10-minute hard limit.
        // See:
        // https://docs.github.com/en/apps/creating-github-apps/authenticating-with-a-github-app/generating-a-json-web-token-jwt-for-a-github-app
        return Jwts.builder()
                .issuer(appId)
                .issuedAt(Date.from(now.minus(60, ChronoUnit.SECONDS)))
                .expiration(Date.from(now.plus(9, ChronoUnit.MINUTES)))
                .signWith(privateKey, Jwts.SIG.RS256)
                .compact();
    }

    /**
     * Accepts both PKCS#1 ("BEGIN RSA PRIVATE KEY", as generated by GitHub)
     * and PKCS#8 ("BEGIN PRIVATE KEY"). BouncyCastle handles both transparently.
     *
     * {@code private-key-pem} must be provided as either a well-formed PEM string
     * or a base64-encoded PEM string.
     */
    private static PrivateKey parsePrivateKey(String pem) {
        String normalizedPem = normalizePemInput(pem);
        try (PEMParser parser = new PEMParser(new StringReader(normalizedPem))) {
            Object obj = parser.readObject();
            if (obj instanceof PEMKeyPair keyPair) {
                return new JcaPEMKeyConverter().getPrivateKey(keyPair.getPrivateKeyInfo());
            }
            if (obj instanceof org.bouncycastle.asn1.pkcs.PrivateKeyInfo keyInfo) {
                return new JcaPEMKeyConverter().getPrivateKey(keyInfo);
            }
            throw new IllegalArgumentException(
                    "Unrecognised PEM object — provide GitHub App private key as raw PEM text or a base64-encoded PEM string. "
                            + "Got: "
                            + (obj == null
                                    ? "null (no PEM header found)"
                                    : obj.getClass().getName()));
        } catch (IOException e) {
            throw new IllegalArgumentException("Failed to parse GitHub App private key from PEM", e);
        }
    }

    private static String normalizePemInput(String pem) {
        String value = pem == null ? "" : pem.trim();
        try {
            return new String(Base64.getDecoder().decode(value), StandardCharsets.UTF_8).trim();
        } catch (IllegalArgumentException e) {
            return value;
        }
    }
}
