platform-integration:
  jwt-groups:
    enabled: true
    claim-name: groups
    mappings:
      - claim-values: [developers]
        team-code: wow
  security:
    oauth2:
      login-providers:
        - dex      