apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}-postgresql
type: Opaque
stringData:
  username: {{ .Values.auth.username | quote }}
  password: {{ .Values.auth.password | quote }}
  database: {{ .Values.auth.database | quote }}
