networks:
  supportbot-ldap:
    external: true
    name: supportbot-ldap

services:
  dex:
    image: ghcr.io/dexidp/dex:v2.45.1@sha256:8499afd690c437f52301efd2b05b2455da5bd2dfc20332cd697dc9937f808462
    command: ["dex", "serve", "/etc/dex/config.yaml"]
    ports:
      - "5556:5556"
      - "5558:5558"
    volumes:
      - ./config/config.yaml:/etc/dex/config.yaml:ro
      - ./web/themes/supportbot:/srv/dex/web/themes/supportbot:ro
      - ./web/templates/header.html:/srv/dex/web/templates/header.html:ro
      - ./web/templates/footer.html:/srv/dex/web/templates/footer.html:ro
      - ./web/templates/login.html:/srv/dex/web/templates/login.html:ro
      - ./web/templates/password.html:/srv/dex/web/templates/password.html:ro
      - ./web/templates/error.html:/srv/dex/web/templates/error.html:ro
      - dex-data:/var/dex
    restart: unless-stopped
    networks:
      - default
      - supportbot-ldap

volumes:
  dex-data:
