networks:
  supportbot-ldap:
    external: true
    name: supportbot-ldap

services:
  dex:
    image: ghcr.io/dexidp/dex:v2.44.0
    command: ["dex", "serve", "/etc/dex/config.yaml"]
    ports:
      - "5556:5556"
      - "5558:5558"
    volumes:
      - ./config/config.yaml:/etc/dex/config.yaml:ro
      - dex-data:/var/dex
    restart: unless-stopped
    networks:
      - default
      - supportbot-ldap

volumes:
  dex-data:
