# Backstage override configuration for your production environment

app:
  baseUrl: "${BASE_URL}"

backend:
  baseUrl: "${BASE_URL}"
  csp:
    img-src: ["'self'", 'data:', 'https:']



# no auth & permission setup for now
auth:
  providers:
    guest:
      dangerouslyAllowOutsideDevelopment: true
