---
name: LDAP Fast Feedback

on:
  workflow_dispatch:
  push:
    branches:
      - main
    paths:
      - ldap/**
      - api/k8s/ldap/**
      - api/k8s/ldap/chart/**

  pull_request:
    branches:
      - main
    paths:
      - ldap/**
      - api/k8s/ldap/**
      - api/k8s/ldap/chart/**

permissions:
  contents: write
  id-token: write
  pull-requests: write

jobs:
  version:
    uses: coreeng/p2p/.github/workflows/p2p-version.yaml@v1
    with:
      version-prefix: ldap/v
    secrets:
      git-token: ${{ secrets.GITHUB_TOKEN }}
      slack_webhook_url: ${{ secrets.P2P_SLACK_WEBHOOK_URL }}

  fastfeedback:
    needs: [version]
    uses: coreeng/p2p/.github/workflows/p2p-workflow-fastfeedback.yaml@v1
    secrets:
      slack_webhook_url: ${{ secrets.P2P_SLACK_WEBHOOK_URL }}
      env_vars: |
        LDAP_BOOTSTRAP_USER_PASSWORD=${{ secrets.LDAP_BOOTSTRAP_USER_PASSWORD }}
    with:
      app-name: ldap
      tenant-name: support-bot
      version: ${{ needs.version.outputs.version }}
      working-directory: ldap
