name: Release

on:
  push:
    tags: ['v*']

jobs:
  publish:
    runs-on: ubuntu-latest
    permissions:
      packages: write
      contents: read
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          distribution: 'graalvm'
          java-version: 21
      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v4
      - name: Lint and test
        run: make check
      - name: Docker push
        run: |
          echo "Building and pushing docker image with tag '${{ github.ref_name }}"
          make "TAG=${{ github.ref_name }}" PUBLISH=true "USERNAME=${{ github.actor }}" "PASSWORD=${{ secrets.GITHUB_TOKEN }}" docker-build
