name: Snyk Vulnerability Check

on:
  pull_request:

jobs:
  security:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'

      - name: Set up Snyk CLI
        uses: snyk/actions/setup@master
        with:
          version: 'latest'

      - name: Run Snyk test
        id: snyk_test
        continue-on-error: true
        run: |
          snyk test api --severity-threshold=critical --sarif-file-output=snyk.sarif
          echo "snyk_exit_code=$?" >> $GITHUB_OUTPUT
        env:
          SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}


      - name: Upload Snyk SARIF to GitHub Security tab
        uses: github/codeql-action/upload-sarif@v3
        with:
          sarif_file: snyk.sarif

      - name: Fail workflow if critical vulnerabilities found
        if: steps.snyk_test.outputs.snyk_exit_code != '0'
        run: exit 1