name: support-bot Prod

on:
  workflow_dispatch:
  schedule:
    - cron: '30 5 * * 1-5'

permissions:
  contents: read
  id-token: write

jobs:
  get-latest-version:
    uses: coreeng/p2p/.github/workflows/p2p-get-latest-image-prod.yaml@p2p-v2-test
    with:
      image-name: support-bot-ui

  prod:
    needs: [get-latest-version]
    uses: coreeng/p2p/.github/workflows/p2p-workflow-prod.yaml@p2p-v2-test
    secrets:
      env_vars: ${{ secrets.env_vars }}
    with:
      app-name: support-bot
      version: ${{ needs.get-latest-version.outputs.version }}
      version-prefix: v
      working-directory: ./
