---
name: support-bot Extended Test

on:
  workflow_dispatch:
  schedule:
    - cron: '0 22 * * *'

permissions:
  contents: read
  id-token: write

jobs:
  get-latest-version:
    uses: coreeng/p2p/.github/workflows/p2p-get-latest-image-extended-test.yaml@v1
    secrets:
      slack_webhook_url: ${{ secrets.P2P_SLACK_WEBHOOK_URL }}
    with:
      image-name: support-bot
      tenant-name: support-bot

  extendedtests:
    needs: [get-latest-version]
    uses: coreeng/p2p/.github/workflows/p2p-workflow-extended-test.yaml@v1
    secrets:
      slack_webhook_url: ${{ secrets.P2P_SLACK_WEBHOOK_URL }}
      env_vars: |
        SLACK_TOKEN=${{ secrets.SLACK_TOKEN_INTEGRATION }}
        SLACK_SOCKET_TOKEN=${{ secrets.SLACK_SOCKET_TOKEN_INTEGRATION }}
        SLACK_SIGNING_SECRET=${{ secrets.SLACK_SIGNING_SECRET_INTEGRATION }}
        AZURE_TENANT_ID=${{ secrets.AZURE_TENANT_ID_INTEGRATION }}
        AZURE_CLIENT_ID=${{ secrets.AZURE_CLIENT_ID_INTEGRATION }}
        AZURE_CLIENT_SECRET=${{ secrets.AZURE_CLIENT_SECRET_INTEGRATION }}
        DEX_CLIENT_ID=${{ secrets.DEX_CLIENT_ID }}
        DEX_CLIENT_SECRET=${{ secrets.DEX_CLIENT_SECRET }}
        LDAP_BOOTSTRAP_USER_PASSWORD=${{ secrets.LDAP_BOOTSTRAP_USER_PASSWORD }}
    with:
      app-name: support-bot
      tenant-name: support-bot
      version: ${{ needs.get-latest-version.outputs.version }}
      version-prefix: v
      working-directory: ./
