name: Trivy Vulnerability Scan

on:
  pull_request:

jobs:
  trivy-scan:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
        with:
          ref: ${{ github.head_ref }}

      - name: Set up Trivy
        uses: aquasecurity/trivy-action@0.28.0
        with:
          scan-type: 'fs'
          ignore-unfixed: 'true'
          exit-code: '1'
          vuln-type: 'os,library'
          format: 'table'
          severity: 'HIGH,CRITICAL'